# Generated by Django 4.1.4 on 2022-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('rno', models.TextField()),
                ('dept', models.TextField()),
                ('problem', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
